daylisoft_web/apps/daylisoft_admin/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('',
    url(r'^$', inicio, name="url_inicio"),

    url(r'^productos/$', listar_productos, name="url_listar_productos"),
    url(r'^productos/agregar/$', form_agregar_producto, name="url_form_agregar_producto"),
    url(r'^productos/agregar/(?P<id_prod>\d+)/$', form_editar_producto, name="url_form_editar_producto"),
    url(r'^productos/add_1', agregar_productos_p1, name="url_agregar_productos_p1"),
    url(r'^productos/add_2', agregar_productos_p2, name="url_agregar_productos_p2"),
    url(r'^productos/add_3', agregar_productos_p3, name="url_agregar_productos_p3"),
    url(r'^productos/add_4', agregar_productos_p4, name="url_agregar_productos_p4"),
    url(r'^productos/eliminar', eliminar_productos, name="url_eliminar_productos"),
    url(r'^productos/filtrar', filtrar_nombre_producto, name="url_filtrar_nombre_producto"),

    url(r'^productos/cuarentena/$', productos_cuarentena, name="url_productos_cuarentena"),
    url(r'^productos/cuarentena/cargar', cargar_cuarentena, name="url_cargar_cuarentena"),
    url(r'^productos/cuarentena/agregar', agregar_cuarentena, name="url_agregar_cuarentena"),
    url(r'^productos/cuarentena/restaurar', restaurar_cuarentena, name="url_restaurar_cuarentena"),

    url(r'^productos/categoria/$', listar_categorias_tabla, name="url_listar_categorias_tabla"),
    url(r'^productos/categorias/select', cargar_categorias_select, name="url_cargar_categorias_select"),
    url(r'^productos/categorias/agregar', agregar_categoria, name="url_agregar_categoria"),
    url(r'^productos/categorias/cargar', cargar_categoria, name="url_cargar_categoria"),
    url(r'^productos/categorias/eliminar', eliminar_categoria, name="url_eliminar_categoria"),

    url(r'^productos/marcas/$', listar_marcas, name="url_listar_marcas"),
    url(r'^productos/marcas/agregar', agregar_marca, name="url_agregar_marca"),
    url(r'^productos/marcas/cargar', cargar_marca, name="url_cargar_marca"),
    url(r'^productos/marcas/eliminar', eliminar_marca, name="url_eliminar_marca"),

    url(r'^productos/tags/$', listar_tags, name="url_listar_tags"),
    url(r'^productos/tags/agregar', agregar_tags, name="url_agregar_tags"),
    url(r'^productos/tags/cargar', cargar_tags, name="url_cargar_tags"),
    url(r'^productos/tags/eliminar', eliminar_tags, name="url_eliminar_tags"),

    url(r'^productos/imagenes/$', listar_imagenes, name="url_listar_imagenes"),
    url(r'^productos/imagenes/eliminar', eliminar_imagenes, name="url_eliminar_imagenes"),
    url(r'^productos/imagenes/cambiar', cambiar_imagenes, name="url_cambiar_imagenes"),
    url(r'^productos/imagenes/subir', subir_nueva_imagen, name="url_subir_nueva_imagen"),

    url(r'^productos/ofertas/$', listar_ofertas, name="url_listar_ofertas"),
    url(r'^productos/ofertas/agregar', agregar_ofertas, name="url_agregar_ofertas"),
    url(r'^productos/ofertas/cargar', cargar_ofertas, name="url_cargar_ofertas"),
    url(r'^productos/ofertas/eliminar', eliminar_ofertas, name="url_eliminar_ofertas"),

    url(r'^productos/reviews/$', listar_reviews, name="url_listar_reviews"),
    url(r'^productos/reviews/eliminar', eliminar_reviews, name="url_eliminar_reviews"),

    url(r'^proveedores/$', listar_proveedores, name="url_listar_proveedores"),
    url(r'^proveedores/agregar/$', form_agregar_proveedor, name="url_form_agregar_proveedor"),
    url(r'^proveedores/agregar/(?P<id_prov>\d+)/$', form_editar_proveedor, name="url_form_editar_proveedor"),
    url(r'^proveedores/eliminar', eliminar_proveedores, name="url_eliminar_proveedores"),
    url(r'^proveedores/add', agregar_proveedor, name="url_agregar_proveedor"),
    url(r'^proveedores/activar', activar_proveedor, name="url_activar_proveedor"),

    url(r'^clientes/$', listar_clientes, name="url_listar_clientes"),
    url(r'^clientes/agregar/$', form_agregar_cliente, name="url_form_agregar_cliente"),
    url(r'^clientes/agregar/(?P<id_cli>\d+)/$', form_editar_cliente, name="url_form_editar_cliente"),
    url(r'^clientes/add', agregar_cliente, name="url_agregar_cliente"),
    url(r'^clientes/eliminar', eliminar_clientes, name="url_eliminar_clientes"),
    url(r'^clientes/activar', activar_clientes, name="url_activar_clientes"),
    url(r'^clientes/superusuario', superusuario_cliente, name="url_superusuario_cliente"),
    url(r'^clientes/cambio', cambio_clave_cliente, name="url_cambio_clave_cliente"),

    url(r'^transporte/$', listar_transporte, name="url_listar_transporte"),
    url(r'^transporte/agregar', agregar_transporte, name="url_agregar_transporte"),
    url(r'^transporte/cargar', cargar_transporte, name="url_cargar_transporte"),
    url(r'^transporte/eliminar', eliminar_transporte, name="url_eliminar_transporte"),

    url(r'^impuesto/$', listar_impuestos, name="url_listar_impuestos"),
    url(r'^impuesto/agregar', agregar_impuestos, name="url_agregar_impuestos"),
    url(r'^impuesto/cargar', cargar_impuestos, name="url_cargar_impuestos"),
    url(r'^impuesto/eliminar', eliminar_impuestos, name="url_eliminar_impuestos"),
    url(r'^impuesto/actual', impuesto_actual, name="url_impuesto_actual"),

    url(r'^empresa/$', form_perfil_empresa, name="url_perfil_empresa"),
    url(r'^empresa/actualizar', actualizar_perfil_empresa, name="url_actualizar_perfil_empresa"),

    url(r'^pedidos/$', listar_pedidos, name="url_listar_pedidos"),
    url(r'^pedidos/(?P<id_ped>\d+)/$', ver_detalle_pedido, name="url_ver_detalle_pedido"),
    url(r'^pedidos/deposito', cargar_deposito, name="url_cargar_deposito"),
    url(r'^pedidos/cliente', cargar_ped_cliente, name="url_cargar_ped_cliente"),
    url(r'^pedidos/estado', cambiar_estado_pedidos, name="url_cambiar_estado_pedidos"),
    url(r'^pedidos/eliminar', eliminar_pedido, name="url_eliminar_pedido"),

    url(r'^notificaciones/$', listar_productos_bajo_stock, name="url_listar_productos_bajo_stock"),
    url(r'^notificaciones/pedidos/$', listar_pedidos_pendientes, name="url_listar_pedidos_pendientes"),

    url(r'^email/$', listar_email, name="url_listar_email"),
    url(r'^email/agregar/$', form_agregar_email, name="url_form_agregar_email"),
    url(r'^email/agregar/(?P<id_email>\d+)/$', form_editar_email, name="url_form_editar_email"),
    url(r'^email/historial/$', listar_historial_email, name="url_listar_historial_email"),

    url(r'^tags/', cargar_todos_tags, name="url_cargar_todos_tags"),

    url(r'^consulta/productos/', json_productos, name="url_json_productos"),

    url(r'^compras/$', reporte_compras, name="url_reporte_compras"),
    url(r'^ventas/$', reporte_ventas, name="url_reporte_ventas"),
)

daylisoft_web/daylisoft_web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

#Internacionalizacion para javascript
js_info_dict = {
    'domain': 'djangojs',
    'packages': ('wrnpro', ),
}

urlpatterns =patterns ('',
    url(r'^user/', include('apps.users.urls', namespace="users_app")),
    url(r'^', include('apps.portal.urls', namespace="portal_app")),
	url(r'blog/', include('apps.blog.urls', namespace="blog_app")),
    url(r'^shop/', include('apps.shop.urls', namespace="shop_app")),
	url(r'^proyectos/', include('apps.proyectos.urls', namespace="proyectos_app")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('apps.daylisoft_admin.urls', namespace="dashboard_app")),

    # Internacionalizacion
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^rosetta/', include('rosetta.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
)

daylisoft_web/templates/dashboard/proveedor/administrar.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block titulo %}{% trans "Daylisoft: Administrar proveedores" %}{% endblock titulo %}
{% block estilos %}
{% endblock estilos %}

<!--Notificacion de productos por debajo del stock-->
{% block notif_prod_numero %}
    {% if notif_stock|length > 0 %}
        <span class="label label-danger">{{ notif_stock|length }}</span>
    {% endif %}
{% endblock notif_prod_numero %}

{% block notif_prod_mensaje %}
    {% for p in notif_stock%}
        <li>
            <a href="{% url 'dashboard_app:url_form_editar_producto' id_prod=p.pro_id %}">
                <div class="pull-left">
                    <img src="{% if p.pro_imagen_principal %}
                    {% for i in p.pro_imagen_principal %}
                        {{ i.img_data.url }}
                    {% endfor %}
                    {% else %}{% static 'daylisoft/dashboard/img/no-imagen.png' %}{% endif %}" class="img-circle" />
                </div>
                <h4 style="padding-bottom:6px; font-weight: 600;">{{ p.pro_nombre|truncatechars:20 }} <span class="label label-danger">{% trans "Stock" %}: {{ p.pro_stock }}</span></h4>
                <p>{% trans "Categoría" %}: {{ p.categorias.cat_nombre}}</p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_prod_mensaje %}

{% block notif_prod_ver %}
    {% if notif_stock %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_productos_bajo_stock' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

<!--Notificacion de pedidos pendientes-->
{% block notif_pedido_numero %}
    {% if notif_pedidos|length > 0 %}
        <span class="label label-warning">{{ notif_pedidos|length }}</span>
    {% endif %}
{% endblock notif_pedido_numero %}

{% block notif_pedidos_mensaje %}
    {% for p in notif_pedidos%}
        <li>
            <a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">
                <h4 style="padding-bottom:6px">
                    {% trans "Cód:" %} {{ p.ped_id }} <small>{% trans "Cliente" %}:  {{ p.cliente.us_nombre }} {{ p.cliente.us_apellidos }}</small>
                </h4>
                <p style="padding-bottom:6px">$ {{ p.ped_total_pagar }}
                <span class="label label-{% if p.ped_estado == 'pendiente' %}warning{% else %}info{% endif %}" style="margin-left: 50px; font-size: 12px;">{{ p.ped_estado|capfirst }}</span></p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_pedidos_mensaje %}

{% block notif_pedidos_ver %}
    {% if notif_pedidos %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

{% block contenido %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header box-header-background with-border">
                        <h3 class="box-title ">{% trans "Administrar proveedores" %}</h3>
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered table-striped" id="tabla_proveedores">
                            <thead >
                            <tr>
                                <th class="active">{% trans "Nombre del proveedor" %}</th>
                                <th class="active">{% trans "Contacto" %}</th>
                                <th class="active">{% trans "Teléfonos" %}</th>
                                <th class="active">{% trans "Ubicación" %}</th>
                                <th class="active">{% trans "Sitio web" %}</th>
                                <th class="active">{% trans "Acción" %}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for p in proveedores%}
                                <tr class="custom-tr">
                                    <td class="vertical-td">{{ p.prov_nombre }}</td>
                                    <td class="vertical-td">{{ p.prov_contacto }}</td>
                                    <td class="vertical-td" style="font-size: 17px">
                                        <span class="label label-success">{{ p.prov_telefono }}</span>&nbsp;&nbsp;
                                        <span class="label label-success">{{ p.prov_cel }}</span>
                                    </td>
                                    <td class="vertical-td">{{ p.prov_ciudad }}, {{ p.prov_pais }}</td>
                                    <td class="vertical-td">{% if p.prov_home_page %}<a target="_blank" href="http://{{ p.prov_home_page }}">{{ p.prov_home_page }}</a>{% else %}{% trans "No posee" %}{% endif %}</td>
                                    <td class="vertical-td">
                                        <div class="btn-group">
                                            <a href="#" class="btn btn-primary btn-xs" title="{% trans 'Ver' %}" data-toggle="modal" data-target="#modal_detalle_producto"><i class="glyphicon glyphicon-search"></i></a>
                                            <a href="{% url 'dashboard_app:url_form_editar_proveedor' id_prov=p.prov_id %}" class="btn bg-navy btn-xs" title="{% trans 'Editar' %}"><i class="glyphicon glyphicon-edit"></i></a>
                                            {% if p.prov_estado %}
                                            <button class="btn btn-danger btn-xs" title="{% trans 'Eliminar' %}" onclick="prod_eliminar_objetos('{% url "dashboard_app:url_eliminar_proveedores" %}?id={{ p.prov_id }}', 'PV', 'tabla_proveedores', this)"><i class="fa fa-trash-o"></i></button>
                                            {% else %}
                                            <button class="btn btn-success btn-xs" title="{% trans 'Activar' %}" onclick="prov_activar_proveedor('{% url "dashboard_app:url_activar_proveedor" %}?id={{ p.prov_id }}', this)"><i class="fa fa-exchange"></i></button>
                                            {% endif %}
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock contenido %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#menu_proveedores').addClass("active");
            $('#menu_proveedores_administrar').addClass("active");
            $('#menu_proveedores_administrar').children('a').removeAttr('href');

            var table = $('#tabla_proveedores').DataTable( {
                pageLength: 15,
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'print',
                        exportOptions: {columns: ':visible'}
                    },
                    {
                        extend: 'excel',
                        exportOptions: {columns: ':visible'},
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {columns: ':visible'},
                    },
                    {
                        extend: 'copy',
                        exportOptions: {columns: ':visible'},
                    },
                    'colvis'
                ]
            });

            table.buttons().container().appendTo('#tabla_proveedores_wrapper .col-sm-6:eq(0)');
        });
    </script>
{% endblock scripts %}

daylisoft_web/templates/dashboard/proveedor/agregar.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block titulo %}{% if not proveedor_editar %}{% trans "Daylisoft: Crear un nuevo proveedor" %}{% else %}{% trans "Daylisoft: Editar proveedor" %}{% endif %}{% endblock titulo %}
{% block estilos %}
{% endblock estilos %}

<!--Notificacion de productos por debajo del stock-->
{% block notif_prod_numero %}
    {% if notif_stock|length > 0 %}
        <span class="label label-danger">{{ notif_stock|length }}</span>
    {% endif %}
{% endblock notif_prod_numero %}

{% block notif_prod_mensaje %}
    {% for p in notif_stock%}
        <li>
            <a href="{% url 'dashboard_app:url_form_editar_producto' id_prod=p.pro_id %}">
                <div class="pull-left">
                    <img src="{% if p.pro_imagen_principal %}
                    {% for i in p.pro_imagen_principal %}
                        {{ i.img_data.url }}
                    {% endfor %}
                    {% else %}{% static 'daylisoft/dashboard/img/no-imagen.png' %}{% endif %}" class="img-circle" />
                </div>
                <h4 style="padding-bottom:6px; font-weight: 600;">{{ p.pro_nombre|truncatechars:20 }} <span class="label label-danger">{% trans "Stock" %}: {{ p.pro_stock }}</span></h4>
                <p>{% trans "Categoría" %}: {{ p.categorias.cat_nombre}}</p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_prod_mensaje %}

{% block notif_prod_ver %}
    {% if notif_stock %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_productos_bajo_stock' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

<!--Notificacion de pedidos pendientes-->
{% block notif_pedido_numero %}
    {% if notif_pedidos|length > 0 %}
        <span class="label label-warning">{{ notif_pedidos|length }}</span>
    {% endif %}
{% endblock notif_pedido_numero %}

{% block notif_pedidos_mensaje %}
    {% for p in notif_pedidos%}
        <li>
            <a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">
                <h4 style="padding-bottom:6px">
                    {% trans "Cód:" %} {{ p.ped_id }} <small>{% trans "Cliente" %}:  {{ p.cliente.us_nombre }} {{ p.cliente.us_apellidos }}</small>
                </h4>
                <p style="padding-bottom:6px">$ {{ p.ped_total_pagar }}
                <span class="label label-{% if p.ped_estado == 'pendiente' %}warning{% else %}info{% endif %}" style="margin-left: 50px; font-size: 12px;">{{ p.ped_estado|capfirst }}</span></p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_pedidos_mensaje %}

{% block notif_pedidos_ver %}
    {% if notif_pedidos %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

{% block contenido %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header box-header-background with-border">
                        <h3 class="box-title ">{% if not proveedor_editar %}{% trans "Crear un nuevo proveedor" %}{% else %}{% trans "Editar proveedor" %}{% endif %}</h3>
                    </div>
                    <form role="form" enctype="multipart/form-data" id="formulario_agregar_proveedor" name="formulario_agregar_proveedor" onsubmit="return false;" method="post">{% csrf_token %}
                        {% if proveedor_editar %}
                            <br />
                            <div align="center"><a href="{% url 'dashboard_app:url_listar_proveedores' %}" class="btn bg-green" >
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> {% trans "Regresar a la lista de proveedores" %}</a>
                            </div>
                            <br/>
                        {% endif %}

                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                                <div class="box-body">
                                    <!-- Nombre -->
                                    {% trans "Nombre del proveedor" as i18n_proveedor_nombre %}
                                    <div class="form-group">
                                        <label>{{ i18n_proveedor_nombre }} <span class="required">*</span></label>
                                        <input type="text" id="proveedor_nombre" name="proveedor_nombre" placeholder="{{ i18n_proveedor_nombre }}" value="{{ proveedor_editar.prov_nombre}}" class="form-control" maxlength="50" required>
                                    </div>
                                    <!-- Contacto -->
                                    {% trans "Contacto" as i18n_proveedor_contacto %}
                                    <div class="form-group">
                                        <label>{{ i18n_proveedor_contacto }} <span class="required">*</span></label>
                                        <input type="text" id="proveedor_contacto" name="proveedor_contacto" placeholder="{{ i18n_proveedor_contacto }}" value="{{ proveedor_editar.prov_contacto}}" class="form-control" maxlength="50" required>
                                    </div>
                                    <!-- Direccion -->
                                    {% trans "Dirección" as i18n_proveedor_direccion %}
                                    <div class="form-group">
                                        <label>{{ i18n_proveedor_direccion }} <span class="required">*</span></label>
                                        <input type="text" id="proveedor_direccion" name="proveedor_direccion" placeholder="{{ i18n_proveedor_direccion }}" value="{{ proveedor_editar.prov_direccion}}" class="form-control" maxlength="50" required>
                                    </div>
                                    <!-- Ciudad -->
                                    {% trans "Ciudad" as i18n_proveedor_ciudad %}
                                    <div class="form-group">
                                        <label>{{ i18n_proveedor_ciudad }} <span class="required">*</span></label>
                                        <input type="text" id="proveedor_ciudad" name="proveedor_ciudad" placeholder="{{ i18n_proveedor_ciudad }}" value="{{ proveedor_editar.prov_ciudad}}" class="form-control" maxlength="20" required>
                                    </div>
                                    <!-- Pais -->
                                    {% trans "País" as i18n_proveedor_pais %}
                                    <div class="form-group">
                                        <label>{{ i18n_proveedor_pais }} <span class="required">*</span></label>
                                        <input type="text" id="proveedor_pais" name="proveedor_pais" placeholder="{{ i18n_proveedor_pais }}" value="{{ proveedor_editar.prov_pais}}" class="form-control" maxlength="10" required>
                                    </div>
                                    <!-- Telefono/Celular -->
                                    <div class="row">
                                        {% trans "Teléfono" as i18n_proveedor_telefono %}
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>{{ i18n_proveedor_telefono }} <span class="required">*</span></label>
                                                <input type="text" id="proveedor_telefono" name="proveedor_telefono" placeholder="{{ i18n_proveedor_telefono }}" value="{{ proveedor_editar.prov_telefono}}" class="form-control" maxlength="10" required>
                                            </div>
                                        </div>
                                        {% trans "Celular" as i18n_proveedor_celular %}
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>{{ i18n_proveedor_celular }} <span class="required">*</span></label>
                                                <input type="text" id="proveedor_celular" name="proveedor_celular" placeholder="{{ i18n_proveedor_celular }}" value="{{ proveedor_editar.prov_cel}}" class="form-control" maxlength="10" required>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Pagina -->
                                    {% trans "Página" as i18n_proveedor_pagina %}
                                    <div class="form-group">
                                        <label>{{ i18n_proveedor_pagina }}</label>
                                        <input type="text" id="proveedor_pagina" name="proveedor_pagina" placeholder="{{ i18n_proveedor_pagina }}" value="{{ proveedor_editar.prov_home_page}}" class="form-control" maxlength="30">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer" align="center">
                            <button onclick="prov_agregar_proveedor('{% url "dashboard_app:url_agregar_proveedor" %}', '{{ proveedor_editar.prov_id }}')" id="btn_proveedores_agregar" class="btn bg-light-blue" type="submit">{% trans "Guardar cambios" %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock contenido %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#menu_proveedores').addClass("active");
            $('#menu_proveedores_agregar').addClass("active");
            $('#menu_proveedores_agregar').children('a').removeAttr('href');
        });
    </script>
{% endblock scripts %}