daylisoft_web/apps/portal/urls.py
from django.conf.urls import patterns, url
from apps.portal.views import *
from apps.portal.tasks import *
urlpatterns = patterns('',
	url(r'^$', inicio, name='index'),
	url(r'^portal/quienesSomos/$', quienesSomos, name='quienesSomos'),
	url(r'^restaurar/$', restaurar, name='restaurar'),
    url(r'^portal/servicios/$', servicios, name='servicios'),
    url(r'^portal/equipo/$', equipo, name='equipo'),
    url(r'^portal/galeria/$', galeriaV, name='galeria'),
    url(r'^portal/contacto/$', contacto, name='contacto'),
    url(r'^portal/enviarmail/$', enviar_correo, name='enviarmail'),
    url(r'^portal/serviciosAdicionales/$', serviciosAdicionales, name='serviciosAdicionales'),
)

daylisoft_web/daylisoft_web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

#Internacionalizacion para javascript
js_info_dict = {
    'domain': 'djangojs',
    'packages': ('wrnpro', ),
}

urlpatterns =patterns ('',
    url(r'^user/', include('apps.users.urls', namespace="users_app")),
    url(r'^', include('apps.portal.urls', namespace="portal_app")),
	url(r'blog/', include('apps.blog.urls', namespace="blog_app")),
    url(r'^shop/', include('apps.shop.urls', namespace="shop_app")),
	url(r'^proyectos/', include('apps.proyectos.urls', namespace="proyectos_app")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('apps.daylisoft_admin.urls', namespace="dashboard_app")),

    # Internacionalizacion
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^rosetta/', include('rosetta.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
)

daylisoft_web/apps/portal/models.py
# -*- coding: utf-8 -*-
from PIL import Image
from django.db import models


# Create your models here.
class portal(models.Model):
	"""docstring for ClassName"""
	por_etiqueta = models.CharField('Etiqueta',max_length=40, blank=True)
	por_texto = models.CharField('Texto',max_length=2000, blank=True)
	por_imagen = models.ImageField('Imagen',upload_to = 'portal', null=True,blank=True)

	def __unicode__(self):
		return self.por_etiqueta
	class Meta:
		verbose_name_plural=u'Textos para el Portal'

class galeria(models.Model):
    gal_etiqueta = models.CharField('Etiqueta',max_length=40, blank=True)
    gal_imagen = models.ImageField('Imagen',upload_to = 'portal/galeria', null=True,blank=True)

    def __unicode__(self):
        return self.gal_etiqueta
    class Meta:
        verbose_name_plural=u'Galeria del Portal'

class redesSociales(models.Model):
    red_id = models.AutoField(primary_key=True)
    red_nombre=models.CharField('Nombre', max_length=50, blank=True)
    red_usuario = models.CharField('Usuario',max_length=200, blank=True)
    red_link= models.CharField('Link',max_length=300, blank=True)
    red_imagen = models.ImageField('Imagen',upload_to = 'portal/redes', null=True,blank=True)

    def __unicode__(self):
        return self.red_nombre
    class Meta:
        verbose_name_plural=u'Redes sociales'

    # def save(self):
    #     if not self.red_imagen:
    #         return

    #     super(redesSociales, self).save()
    #     red_imagen = Image.open(self.red_imagen)
    #     ancho, alto = red_imagen.size
    #     ratio_height = (50*alto)/ancho
    #     size = (160, 42)
    #     red_imagen = red_imagen.resize(size, Image.ANTIALIAS)
    #     red_imagen.save(self.red_imagen.path)

daylisoft_web/apps/portal/views.py
from django.shortcuts import render, render_to_response, RequestContext, HttpResponse, redirect, HttpResponseRedirect
from apps.blog.models import *
from .models import *
from django.contrib import messages
from django.core.mail import send_mail




# Create your views here.
def inicio(request):
	context={}
	context['redes']=redesSociales.objects.all()
	return render_to_response('index.html', context, context_instance=RequestContext(request))

def quienesSomos(request):
	context={}
	context['acerca'] = portal.objects.get(por_etiqueta='acerca')
	context['mision'] = portal.objects.get(por_etiqueta='mision')
	context['vision'] = portal.objects.get(por_etiqueta='vision')
	context['fundador'] = portal.objects.get(por_etiqueta='fundador')
	context['cofundador'] = portal.objects.get(por_etiqueta='co-fundador')
	context['administrador'] = portal.objects.get(por_etiqueta='gerente')
	context['redes']=redesSociales.objects.all()
	return render_to_response('portal/quienesSomos.html', context, context_instance=RequestContext(request))

def servicios(request):
	context={}
	context['redes']=redesSociales.objects.all()
	return render_to_response('portal/servicios.html', context, context_instance=RequestContext(request))

def equipo(request):
	context={}
	context['fundador'] = portal.objects.get(por_etiqueta='fundador')
	context['cofundador'] = portal.objects.get(por_etiqueta='co-fundador')
	context['administrador'] = portal.objects.get(por_etiqueta='gerente')
	context['redes']=redesSociales.objects.all()
	return render_to_response('portal/equipo.html', context, context_instance=RequestContext(request))

def galeriaV(request):
	context={}
	context['galeria'] = galeria.objects.all()
	context['redes']=redesSociales.objects.all()
	return render_to_response('portal/galeria.html', context, context_instance=RequestContext(request))


def contacto(request):
	context={}
	context['galeria'] = galeria.objects.all()
	context['redes']=redesSociales.objects.all()
	return render_to_response('portal/contactenos.html', context, context_instance=RequestContext(request))


def enviar_correo(request):
    data = []
    if request.method == "POST":
        if request.user.is_authenticated():
            tema = request.POST["tema"]
            mensaje = request.POST["mensaje"]
            nombre=request.user
            email = request.user.email
            print(email)
        else:
            nombre = request.POST["nombre"]
            email = request.POST["email"]
            tema = request.POST["tema"]
            mensaje = request.POST["mensaje"]
        email_subject = tema
        email_body = mensaje
        send_mail(email_subject, email_body, email,['daylisoft@gmail.com'], fail_silently=False)
        messages.add_message(request, messages.SUCCESS, 'Su Mensaje se ha enviado')
    return redirect('/portal/contacto/')


def serviciosAdicionales(request):
    context={}
    context['redes']=redesSociales.objects.all()
    return render_to_response('portal/otros_servicios.html', context, context_instance=RequestContext(request))

daylisoft_web/apps/portal/templates/portal/contactenos.html
{% extends "base.html" %} {% load static %} {% block css %} {% endblock css %} {% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="page_title_block">
                <div class="bg_title">
                    <h2>Dí Hola</h2>
                </div>
                <div class="page_descr">
                    <p>¡Escríbenos un mensaje para ayudarte en lo que necesites!</p>
                </div>
            </div>
            <div class="content_block row no-sidebar">
                <div class="fl-container">
                    <div class="posts-block">
                        <div class="contentarea">
                            <div class="row">
                                <div class="col-sm-9 module_cont pb20 animate" data-anim-type="fadeInLeft" data-anim-delay="300">
                                    <h3 class="mb27 mt_5">Escríbenos un mail</h3>
                                    <div class="module_content contact_form">
                                        <div id="note"></div>
                                        <div id="fields">
                                        <form id="ajax-contact-form1" method="post" action="{% url 'portal_app:enviarmail' %}">{% csrf_token %}
                                            {% if request.user.is_authenticated %}
                                                <div class="row row20">
                                            {% else %}
                                                <div class="row row20">
                                                    <div class="col-sm-12"><input type="text" name="nombre" id="nombre" value="" placeholder="Nombre *" /></div>
                                                    <div class="col-sm-12"><input type="text" name="email" id="email" value="" placeholder="Email *" /></div>
                                            {% endif %}
                                                      <div class="col-sm-12"><input type="text" name="tema" id="tema" value="" placeholder="Título" /></div>
                                                </div>
                                                <textarea name="mensaje" id="mensaje" placeholder="Escriba su mensaje aquí..."></textarea>
                                                <input type="submit" value="Enviar mensaje">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3 module_cont contact_info pb40 animate" data-anim-type="fadeInRight" data-anim-delay="300">
                                    <h3 class="mb20 mt_5">Información de contacto</h3>
                                    <p><span>Número:</span> +593 990171512</p>
                                    <p><span>Oficina:</span> Quito, Ecuador</p>
                                    <p class="mb29"><span>Email:</span> <a href="mailto:#">daylisoft@gmail.com</a></p>

                                    <h3 class="mb26">Siguenos en</h3>
                                    <div class="shortcode_icons_wrapper">
                                        <a href="https://www.facebook.com/daylisoft/" title="Facebook"><span><i class="icon-facebook"></i></span></a>
                                        <a href="https://twitter.com/daylisoft" title="Twitter"><span><i class="icon-twitter"></i></span></a>
                                        <a href="https://plus.google.com/u/0/109232023950965083720" title="Google+"><span><i class="icon-google-plus"></i></span></a>
                                        <a href="https://www.linkedin.com/in/dayli-soft-b8715a12a" title="Linkedin"><span><i class="icon-linkedin"></i></span></a>
                                        <a href="https://instagram.com/daylisoft" title="Instagram"><span><i class="icon-instagram"></i></span></a>
                                    </div>
                                </div>
                            </div>

                            <div class="fw_block bg_start wall_wrap full_map mb0">
                                <div class="row">
                                    <div class="col-sm-12 module_cont pb0 module_google_map">
                                        <div class="module_content">
                                            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15932.377050300069!2d-79.80674575344239!3d-3.326885086041365!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb7d2e392ffa05f65!2sDaylisoft+Cia+Ltda!5e0!3m2!1ses!2sec!4v1480196393689" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}
    <script>
        $("#menu_contactenos").addClass("current-menu-parent");
    </script>
{% endblock js %}

daylisoft_web/apps/portal/templates/portal/galeria.html
{% extends "base.html" %} {% load static %} {% block css %} {% endblock css %} {% block content %}
<div class="breadcrumbs">
    <div class="container">
        <a href="/">Inicio</a><span>/</span>Galería
        <h1 class="title-page">Galería</h1>
    </div>
</div>
<div class="wrapper">
    <div class="container">
        <div class="content_block row no-sidebar">
            <div class="fl-container">
                <div class="posts-block">
                    <div class="contentarea">
                        <div class="row">
                            <div class="col-sm-12 module_cont pb80 module_gallery photo_gallery">
                                <div class="featured_items">
                                    <div class="items4 featured_portfolio">
                                        <ul class="item_list">
                                        {% for objeto in galeria %}
                                            <li class="animate" data-anim-type="bounceIn" data-anim-delay="250">
                                                <div class="item">
                                                    <div class="gallery_item_padding">
                                                        <div class="gallery_item_wrapper">
                                                            <img src="{{objeto.gal_imagen.url}}" alt="" />
                                                            <span class="block_fade"></span>
                                                            <div class="post_hover_info">
                                                                <a href="{{objeto.gal_imagen.url}}" class="photozoom view_link"><i class="icon-expand"></i></a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                        {% endfor %}
                                        </ul>
                                     </div>
                                </div>
                            </div>
                        </div>

                        <div class="fw_block bg_start grey_bg pt46 mb0">
                            <div class="row">
                                <div class="col-sm-12 module_cont pb47 module_partners">
                                    <div class="module_content sponsors_works items6">
                                        <ul>
                                            {% for objeto in redes %}
                                                <li class="animate" data-anim-type="bounceIn" data-anim-delay="250">
                                                    <div class="item_wrapper">
                                                        <div class="item">
                                                            <a href="{{objeto.red_link}}" target="_blank"><img src="{{objeto.red_imagen.url}}" alt="" /></a>
                                                        </div>
                                                    </div>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                             </div>
                         </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block js %}
    <script>
        $("#menu_paginas").addClass("current-menu-parent");
    </script>
{% endblock js %}

daylisoft_web/apps/portal/templates/portal/otros_servicios.html
{% extends "base.html" %} {% load static %} {% block css %} {% endblock css %} {% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="content_block row no-sidebar single_post">
                <div class="fl-container">
                    <div class="posts-block">
                        <div class="contentarea">
                            <div class="blog_post_preview animate" data-anim-type="fadeInUp" data-anim-delay="300">
                                <h1>Lo que ofrecemos</h1>
                                <div class=" blog_post_image">
                                                        <div class="slider-wrapper theme-default">
                                                            <div class="nivoSlider">
                                                                    <img  src="/static/daylisoft/img/portal/servicios/1z.jpg" alt="">
                                                                    <img   height="42" width="42" src="/static/daylisoft/img/portal/servicios/2z.jpg" alt="">
                                                                    <img  height="42" width="42"align=" " src="/static/daylisoft/img/portal/servicios/3z.jpg" alt="">
                                                                    <img  height="42" width="42" src="/static/daylisoft/img/portal/servicios/4z.jpg" alt="">
                                                                    <img  height="42" width="42" src="/static/daylisoft/img/portal/servicios/5z.jpg" alt="">
                                                                    <img  src="/static/daylisoft/img/portal/servicios/r1z.jpg" alt="">
                                                                    <img  src="/static/daylisoft/img/portal/servicios/r2z.jpg" alt="">
                                                                    <img  src="/static/daylisoft/img/portal/servicios/ct1z.jpg" alt="">
                                                                    <img   height="42" width="42" src="/static/daylisoft/img/portal/servicios/ct2z.jpg" alt="">

                                                            </div>
                                                        </div>
                                </div>
                                <div style="background:#eee;border:1px solid #ccc;padding:5px 10px;"><span style="font-family:times new roman,times,serif;"><strong>Mantenimiento de Computadoras
                                </strong></span></div>
                                    <ol style="margin-top: 5px; margin-left: 35px; padding-left: 5px; margin-bottom: 20px; color: rgb(68, 85, 85); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px;">
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Diagn&oacute;stico.</b></li>
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Limpieza.</b></li>
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Formateo de computadoras.</b></li>
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Partición de discos duros</b></li>
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Instalación de antivirus</b></li>
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Optimización de Pc</b></li>
                                    </ol>

                                </div>
                                <div style="background:#eee;border:1px solid #ccc;padding:5px 10px;"><span style="font-family:times new roman,times,serif;"><strong>Instalación de Redes y Cámaras Web</strong></span></div>
                                    <ol style="margin-top: 5px; margin-left: 35px; padding-left: 5px; margin-bottom: 20px; color: rgb(68, 85, 85); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px;">
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Instalación de redes informáticas.</b></li>
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Mantenimiento de infraestructuras de telecomunicaciones</b></li>
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Instalación de Cámaras de seguridad</b></li>
                                    </ol>

                                </div>
                                <div style="background:#eee;border:1px solid #ccc;padding:5px 10px;"><span style="font-family:times new roman,times,serif;"><strong>Consultoría Tecnologíca</strong></span></div>
                                    <ol style="margin-top: 5px; margin-left: 35px; padding-left: 5px; margin-bottom: 20px; color: rgb(68, 85, 85); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px;">
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Entendemos tus necesidades</b></li>
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Analizamos tus proyectos</b></li>
                                        <li style="margin-top: 0px; margin-left: 0px; padding-left: 0px;"><b>Sugerimos alternativas</b></li>
                                    </ol>

                                </div>
                            </div>

                            </div>
                             <div class="fw_block bg_start grey_bg pt46 mb0">
                                <div class="row">
                                    <div class="col-sm-12 module_cont pb47 module_partners">
                                        <div class="module_content sponsors_works items6">
                                            <ul>
                                            {% for objeto in redes %}
                                                <li class="animate" data-anim-type="bounceIn" data-anim-delay="250">
                                                    <div class="item_wrapper">
                                                        <div class="item">
                                                            <a href="{{objeto.red_link}}" target="_blank"><img src="{{objeto.red_imagen.url}}" alt="" /></a>
                                                        </div>
                                                    </div>
                                                </li>
                                            {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                 </div>
                             </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %} {% block js %} {% endblock js %}