daylisoft_web/apps/daylisoft_admin/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('',
    url(r'^$', inicio, name="url_inicio"),

    url(r'^productos/$', listar_productos, name="url_listar_productos"),
    url(r'^productos/agregar/$', form_agregar_producto, name="url_form_agregar_producto"),
    url(r'^productos/agregar/(?P<id_prod>\d+)/$', form_editar_producto, name="url_form_editar_producto"),
    url(r'^productos/add_1', agregar_productos_p1, name="url_agregar_productos_p1"),
    url(r'^productos/add_2', agregar_productos_p2, name="url_agregar_productos_p2"),
    url(r'^productos/add_3', agregar_productos_p3, name="url_agregar_productos_p3"),
    url(r'^productos/add_4', agregar_productos_p4, name="url_agregar_productos_p4"),
    url(r'^productos/eliminar', eliminar_productos, name="url_eliminar_productos"),
    url(r'^productos/filtrar', filtrar_nombre_producto, name="url_filtrar_nombre_producto"),

    url(r'^productos/cuarentena/$', productos_cuarentena, name="url_productos_cuarentena"),
    url(r'^productos/cuarentena/cargar', cargar_cuarentena, name="url_cargar_cuarentena"),
    url(r'^productos/cuarentena/agregar', agregar_cuarentena, name="url_agregar_cuarentena"),
    url(r'^productos/cuarentena/restaurar', restaurar_cuarentena, name="url_restaurar_cuarentena"),

    url(r'^productos/categoria/$', listar_categorias_tabla, name="url_listar_categorias_tabla"),
    url(r'^productos/categorias/select', cargar_categorias_select, name="url_cargar_categorias_select"),
    url(r'^productos/categorias/agregar', agregar_categoria, name="url_agregar_categoria"),
    url(r'^productos/categorias/cargar', cargar_categoria, name="url_cargar_categoria"),
    url(r'^productos/categorias/eliminar', eliminar_categoria, name="url_eliminar_categoria"),

    url(r'^productos/marcas/$', listar_marcas, name="url_listar_marcas"),
    url(r'^productos/marcas/agregar', agregar_marca, name="url_agregar_marca"),
    url(r'^productos/marcas/cargar', cargar_marca, name="url_cargar_marca"),
    url(r'^productos/marcas/eliminar', eliminar_marca, name="url_eliminar_marca"),

    url(r'^productos/tags/$', listar_tags, name="url_listar_tags"),
    url(r'^productos/tags/agregar', agregar_tags, name="url_agregar_tags"),
    url(r'^productos/tags/cargar', cargar_tags, name="url_cargar_tags"),
    url(r'^productos/tags/eliminar', eliminar_tags, name="url_eliminar_tags"),

    url(r'^productos/imagenes/$', listar_imagenes, name="url_listar_imagenes"),
    url(r'^productos/imagenes/eliminar', eliminar_imagenes, name="url_eliminar_imagenes"),
    url(r'^productos/imagenes/cambiar', cambiar_imagenes, name="url_cambiar_imagenes"),
    url(r'^productos/imagenes/subir', subir_nueva_imagen, name="url_subir_nueva_imagen"),

    url(r'^productos/ofertas/$', listar_ofertas, name="url_listar_ofertas"),
    url(r'^productos/ofertas/agregar', agregar_ofertas, name="url_agregar_ofertas"),
    url(r'^productos/ofertas/cargar', cargar_ofertas, name="url_cargar_ofertas"),
    url(r'^productos/ofertas/eliminar', eliminar_ofertas, name="url_eliminar_ofertas"),

    url(r'^productos/reviews/$', listar_reviews, name="url_listar_reviews"),
    url(r'^productos/reviews/eliminar', eliminar_reviews, name="url_eliminar_reviews"),

    url(r'^proveedores/$', listar_proveedores, name="url_listar_proveedores"),
    url(r'^proveedores/agregar/$', form_agregar_proveedor, name="url_form_agregar_proveedor"),
    url(r'^proveedores/agregar/(?P<id_prov>\d+)/$', form_editar_proveedor, name="url_form_editar_proveedor"),
    url(r'^proveedores/eliminar', eliminar_proveedores, name="url_eliminar_proveedores"),
    url(r'^proveedores/add', agregar_proveedor, name="url_agregar_proveedor"),
    url(r'^proveedores/activar', activar_proveedor, name="url_activar_proveedor"),

    url(r'^clientes/$', listar_clientes, name="url_listar_clientes"),
    url(r'^clientes/agregar/$', form_agregar_cliente, name="url_form_agregar_cliente"),
    url(r'^clientes/agregar/(?P<id_cli>\d+)/$', form_editar_cliente, name="url_form_editar_cliente"),
    url(r'^clientes/add', agregar_cliente, name="url_agregar_cliente"),
    url(r'^clientes/eliminar', eliminar_clientes, name="url_eliminar_clientes"),
    url(r'^clientes/activar', activar_clientes, name="url_activar_clientes"),
    url(r'^clientes/superusuario', superusuario_cliente, name="url_superusuario_cliente"),
    url(r'^clientes/cambio', cambio_clave_cliente, name="url_cambio_clave_cliente"),

    url(r'^transporte/$', listar_transporte, name="url_listar_transporte"),
    url(r'^transporte/agregar', agregar_transporte, name="url_agregar_transporte"),
    url(r'^transporte/cargar', cargar_transporte, name="url_cargar_transporte"),
    url(r'^transporte/eliminar', eliminar_transporte, name="url_eliminar_transporte"),

    url(r'^impuesto/$', listar_impuestos, name="url_listar_impuestos"),
    url(r'^impuesto/agregar', agregar_impuestos, name="url_agregar_impuestos"),
    url(r'^impuesto/cargar', cargar_impuestos, name="url_cargar_impuestos"),
    url(r'^impuesto/eliminar', eliminar_impuestos, name="url_eliminar_impuestos"),
    url(r'^impuesto/actual', impuesto_actual, name="url_impuesto_actual"),

    url(r'^empresa/$', form_perfil_empresa, name="url_perfil_empresa"),
    url(r'^empresa/actualizar', actualizar_perfil_empresa, name="url_actualizar_perfil_empresa"),

    url(r'^pedidos/$', listar_pedidos, name="url_listar_pedidos"),
    url(r'^pedidos/(?P<id_ped>\d+)/$', ver_detalle_pedido, name="url_ver_detalle_pedido"),
    url(r'^pedidos/deposito', cargar_deposito, name="url_cargar_deposito"),
    url(r'^pedidos/cliente', cargar_ped_cliente, name="url_cargar_ped_cliente"),
    url(r'^pedidos/estado', cambiar_estado_pedidos, name="url_cambiar_estado_pedidos"),
    url(r'^pedidos/eliminar', eliminar_pedido, name="url_eliminar_pedido"),

    url(r'^notificaciones/$', listar_productos_bajo_stock, name="url_listar_productos_bajo_stock"),
    url(r'^notificaciones/pedidos/$', listar_pedidos_pendientes, name="url_listar_pedidos_pendientes"),

    url(r'^email/$', listar_email, name="url_listar_email"),
    url(r'^email/agregar/$', form_agregar_email, name="url_form_agregar_email"),
    url(r'^email/agregar/(?P<id_email>\d+)/$', form_editar_email, name="url_form_editar_email"),
    url(r'^email/historial/$', listar_historial_email, name="url_listar_historial_email"),

    url(r'^tags/', cargar_todos_tags, name="url_cargar_todos_tags"),

    url(r'^consulta/productos/', json_productos, name="url_json_productos"),

    url(r'^compras/$', reporte_compras, name="url_reporte_compras"),
    url(r'^ventas/$', reporte_ventas, name="url_reporte_ventas"),
)

daylisoft_web/daylisoft_web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

#Internacionalizacion para javascript
js_info_dict = {
    'domain': 'djangojs',
    'packages': ('wrnpro', ),
}

urlpatterns =patterns ('',
    url(r'^user/', include('apps.users.urls', namespace="users_app")),
    url(r'^', include('apps.portal.urls', namespace="portal_app")),
	url(r'blog/', include('apps.blog.urls', namespace="blog_app")),
    url(r'^shop/', include('apps.shop.urls', namespace="shop_app")),
	url(r'^proyectos/', include('apps.proyectos.urls', namespace="proyectos_app")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('apps.daylisoft_admin.urls', namespace="dashboard_app")),

    # Internacionalizacion
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^rosetta/', include('rosetta.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
)

daylisoft_web/templates/dashboard/ajustes/categorias.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block titulo %}{% trans "Daylisoft: Categorías de producto" %}{% endblock titulo %}
{% block estilos %}
{% endblock estilos %}

<!--Notificacion de productos por debajo del stock-->
{% block notif_prod_numero %}
    {% if notif_stock|length > 0 %}
        <span class="label label-danger">{{ notif_stock|length }}</span>
    {% endif %}
{% endblock notif_prod_numero %}

{% block notif_prod_mensaje %}
    {% for p in notif_stock%}
        <li>
            <a href="{% url 'dashboard_app:url_form_editar_producto' id_prod=p.pro_id %}">
                <div class="pull-left">
                    <img src="{% if p.pro_imagen_principal %}
                    {% for i in p.pro_imagen_principal %}
                        {{ i.img_data.url }}
                    {% endfor %}
                    {% else %}{% static 'daylisoft/dashboard/img/no-imagen.png' %}{% endif %}" class="img-circle" />
                </div>
                <h4 style="padding-bottom:6px; font-weight: 600;">{{ p.pro_nombre|truncatechars:20 }} <span class="label label-danger">{% trans "Stock" %}: {{ p.pro_stock }}</span></h4>
                <p>{% trans "Categoría" %}: {{ p.categorias.cat_nombre}}</p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_prod_mensaje %}

{% block notif_prod_ver %}
    {% if notif_stock %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_productos_bajo_stock' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

<!--Notificacion de pedidos pendientes-->
{% block notif_pedido_numero %}
    {% if notif_pedidos|length > 0 %}
        <span class="label label-warning">{{ notif_pedidos|length }}</span>
    {% endif %}
{% endblock notif_pedido_numero %}

{% block notif_pedidos_mensaje %}
    {% for p in notif_pedidos%}
        <li>
            <a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">
                <h4 style="padding-bottom:6px">
                    {% trans "Cód:" %} {{ p.ped_id }} <small>{% trans "Cliente" %}:  {{ p.cliente.us_nombre }} {{ p.cliente.us_apellidos }}</small>
                </h4>
                <p style="padding-bottom:6px">$ {{ p.ped_total_pagar }}
                <span class="label label-{% if p.ped_estado == 'pendiente' %}warning{% else %}info{% endif %}" style="margin-left: 50px; font-size: 12px;">{{ p.ped_estado|capfirst }}</span></p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_pedidos_mensaje %}

{% block notif_pedidos_ver %}
    {% if notif_pedidos %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

{% block contenido %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header box-header-background with-border">
                        <h3 class="box-title ">{% trans "Categorías de producto" %}</h3>
                    </div>
                    <div class="box-background">
                        <form id="formulario_producto_categoria" name="formulario_producto_categoria" role="form" enctype="multipart/form-data" method="post" onsubmit="return false;">{% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                                    <div class="box-body">
                                        {% trans "Categoría" as i18n_nombre_categoria_producto%}
                                        {% trans "Subcategoría" as i18n_nombre_subcategoria_producto%}
                                        <div id="id_tipo_entrada_ui" class="form-group" align="center" style="display: none">
                                            <input id="tipo_entrada" type="checkbox" checked data-toggle="toggle" data-on="{{ i18n_nombre_categoria_producto }}" data-off="{{ i18n_nombre_subcategoria_producto }}" data-onstyle="warning" data-offstyle="info" data-width="110">
                                        </div>
                                        <!-- Categoria -->
                                        {% if categorias %}
                                        {% trans "Seleccione una categoría" as i18n_seleccione_categoria%}
                                        <div id="id_categoria_padre_ui" class="form-group" style="display: none">
                                            <label>{{ i18n_nombre_categoria_producto }}</label>
                                            <select id="id_categoria_padre" name="id_categoria_padre" style="width: 99%;">
                                                <option disabled value="0">{{ i18n_seleccione_categoria }}</option>
                                            </select>
                                        </div>
                                        {% endif %}
                                        <!-- Subcategoria -->
                                        <div class="form-group">
                                            <label id="label_categoria_padre">{{ i18n_nombre_categoria_producto }} </label><span class="required">*</span>
                                            <input id="id_categoria_hijo" name="id_categoria_hijo" type="text" placeholder="{{ i18n_nombre_categoria_producto }}" class="form-control" maxlength="30" required>
                                        </div>
                                        <!-- Descripcion-->
                                        {% trans "Descripción" as i18n_categoria_descripcion %}
                                        <div class="form-group">
                                            <label>{{ i18n_categoria_descripcion }}</label>
                                            <textarea style="resize: none; height: 90px" id="categoria_descripcion" name="categoria_descripcion" class="form-control autogrow" placeholder="{{ i18n_categoria_descripcion }}"></textarea>
                                        </div>
                                        <button onclick="ajus_agregar_categoria('{% url "dashboard_app:url_agregar_categoria" %}')" id="btn_guardar_categoria" type="submit" class="btn bg-light-blue">{% trans "Guardar" %}</button>
                                        <button type="button" onclick="ajus_cancelar_categoria()" class="btn btn-default">{% trans "Cancelar" %}</button><br/><br/><br/><br/>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="box-footer"></div>
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <!-- Tabla -->
                            <table class="table table-bordered table-striped" id="tabla_categorias" cellspacing="0" width="100%">
                                <thead >
                                    <tr>
                                        <th class="active" style="width: 35px;">{% trans "Cód." %}</th>
                                        <th class="active">{% trans "Nombre de la categoría" %}</th>
                                        <th class="active" style="width: 50px;">{% trans "Acción" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for c in categorias %}
                                    <tr class="custom-tr">
                                        <td class="vertical-td">{{ c.cat_id }}</td>
                                        <td class="vertical-td">{{ c.cat_nombre }} {% if c.cat_id_padre_id > 0 %}, <span class="label label-waring"> {{ c.cat_id_padre.cat_nombre}}</span>{% endif %}</td>
                                        <td class="vertical-td">
                                            <div class="btn-group">
                                                <button onclick="ajus_cargar_categoria('{% url "dashboard_app:url_cargar_categoria" %}?id={{ c.cat_id }}', this)" class="btn bg-navy btn-xs" title="{% trans 'Editar' %}"><i class="glyphicon glyphicon-edit"></i></button>
                                                <button onclick="prod_eliminar_objetos('{% url "dashboard_app:url_eliminar_categoria" %}?id={{ c.cat_id }}', 'CC', 'tabla_categorias', this)" class="btn btn-danger btn-xs" title="{% trans 'Eliminar' %}"><i class="fa fa-trash-o"></i></button>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock contenido %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            {% if categorias %}
                cargar_productos_select("{% url 'dashboard_app:url_cargar_categorias_select' %}", "{{ i18n_seleccione_categoria }}", "id_categoria_padre");
                $("#id_tipo_entrada_ui").show();
                $("#id_categoria_padre").val("0");
                $("#id_categoria_padre").select2({ selected: "0" });
            {% endif %}

            $('#menu_ajustes').addClass("active");
            $('#menu_ajustes_categorias').addClass("active");
            $('#menu_ajustes_categorias_administrar').addClass("active");
            $('#menu_ajustes_categorias_administrar').children('a').removeAttr('href');

            var table = $('#tabla_categorias').DataTable({
                lengthChange: false
            });

            //Toggle categoria-subcategoria
            $('#tipo_entrada').change(function() {
                if($(this).prop('checked') == true){
                    $('#id_categoria_padre_ui').hide();
                    $("#label_categoria_padre").text("Categoría");
                    $("#id_categoria_hijo").attr("placeholder", $("#label_categoria_padre").text())
                }else{
                    $('#id_categoria_padre_ui').show();
                    $("#label_categoria_padre").text("Sub-categoría");
                    $("#id_categoria_hijo").attr("placeholder", $("#label_categoria_padre").text())
                }
            });

            $("#menu_ajustes_categorias").data("test", {categoria_id: ""});
        });
    </script>
{% endblock scripts %}

daylisoft_web/templates/dashboard/ajustes/impuestos.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load l10n %}
{% load staticfiles %}

{% block titulo %}{% trans "Daylisoft: Reglas de impuesto" %}{% endblock titulo %}
{% block estilos %}
{% endblock estilos %}

<!--Notificacion de productos por debajo del stock-->
{% block notif_prod_numero %}
    {% if notif_stock|length > 0 %}
        <span class="label label-danger">{{ notif_stock|length }}</span>
    {% endif %}
{% endblock notif_prod_numero %}

{% block notif_prod_mensaje %}
    {% for p in notif_stock%}
        <li>
            <a href="{% url 'dashboard_app:url_form_editar_producto' id_prod=p.pro_id %}">
                <div class="pull-left">
                    <img src="{% if p.pro_imagen_principal %}
                    {% for i in p.pro_imagen_principal %}
                        {{ i.img_data.url }}
                    {% endfor %}
                    {% else %}{% static 'daylisoft/dashboard/img/no-imagen.png' %}{% endif %}" class="img-circle" />
                </div>
                <h4 style="padding-bottom:6px; font-weight: 600;">{{ p.pro_nombre|truncatechars:20 }} <span class="label label-danger">{% trans "Stock" %}: {{ p.pro_stock }}</span></h4>
                <p>{% trans "Categoría" %}: {{ p.categorias.cat_nombre}}</p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_prod_mensaje %}

{% block notif_prod_ver %}
    {% if notif_stock %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_productos_bajo_stock' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

<!--Notificacion de pedidos pendientes-->
{% block notif_pedido_numero %}
    {% if notif_pedidos|length > 0 %}
        <span class="label label-warning">{{ notif_pedidos|length }}</span>
    {% endif %}
{% endblock notif_pedido_numero %}

{% block notif_pedidos_mensaje %}
    {% for p in notif_pedidos%}
        <li>
            <a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">
                <h4 style="padding-bottom:6px">
                    {% trans "Cód:" %} {{ p.ped_id }} <small>{% trans "Cliente" %}:  {{ p.cliente.us_nombre }} {{ p.cliente.us_apellidos }}</small>
                </h4>
                <p style="padding-bottom:6px">$ {{ p.ped_total_pagar }}
                <span class="label label-{% if p.ped_estado == 'pendiente' %}warning{% else %}info{% endif %}" style="margin-left: 50px; font-size: 12px;">{{ p.ped_estado|capfirst }}</span></p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_pedidos_mensaje %}

{% block notif_pedidos_ver %}
    {% if notif_pedidos %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

{% block contenido %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header box-header-background with-border">
                        <h3 class="box-title ">{% trans "Reglas de impuesto" %}</h3>
                    </div>
                    <div class="box-background">
                        <form id="formulario_ajustes_impuesto" name="formulario_ajustes_impuesto" role="form" enctype="multipart/form-data" method="post" onsubmit="return false;" novalidate>{% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                                    <div class="box-body">
                                        {% trans "Nombre del impuesto" as i18n_nombre_impuesto%}
                                        <input id="ajustes_id_impuesto" name="ajustes_id_impuesto" type="hidden">
                                        <!-- Nombre -->
                                        <div class="form-group">
                                            <label>{{ i18n_nombre_impuesto }} </label><span class="required">*</span>
                                            <input id="ajustes_impuesto_nombre" name="ajustes_impuesto_nombre" type="text" placeholder="{{ i18n_nombre_impuesto }}" class="form-control" maxlength="100" required>
                                        </div>
                                        {% trans "Porcentaje (%)" as i18n_porcentaje_impuesto%}
                                        <!-- Porcentaje -->
                                        <div class="form-group">
                                            <label>{{ i18n_porcentaje_impuesto }} </label><span class="required">*</span>
                                            <input id="ajustes_impuesto_porcentaje" name="ajustes_impuesto_porcentaje" type="text" placeholder="{{ i18n_porcentaje_impuesto }}" class="form-control" maxlength="100" required>
                                        </div>
                                        <button id="btn_guardar_impuesto" type="submit" onclick="ajus_agregar_impuesto('{% url "dashboard_app:url_agregar_impuestos" %}')" class="btn bg-light-blue">{% trans "Guardar" %}</button>
                                        <button type="button" onclick="reset_formulario('formulario_ajustes_impuesto','ajustes_impuesto_nombre')" class="btn btn-default">{% trans "Cancelar" %}</button><br/><br/>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="box-footer"></div>
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <!-- Tabla -->
                            <table class="table table-bordered table-striped" id="tabla_impuesto" cellspacing="0" width="100%">
                                <thead >
                                    <tr>
                                        <th class="active">{% trans "Impuesto actual" %}</th>
                                        <th class="active">{% trans "Nombre del impuesto" %}</th>
                                        <th class="active">{% trans "Porcentaje" %}</th>
                                        <th class="active" style="width: 50px;">{% trans "Acción" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for i in impuesto %}
                                    <tr class="custom-tr">
                                        <td class="vertical-td">
                                            <div class="radio">
                                                <label><input onchange="ajus_impuesto_actual('{% url "dashboard_app:url_impuesto_actual" %}?id={{ i.imp_id }}')" type="radio" value="{{ i.imp_id }}" name="impuesto_actual" {% if i.imp_actual %}checked{% endif %}> {% trans "Seleccionar" %}</label>
                                            </div>
                                        </td>
                                        <td class="vertical-td">{{ i.imp_nombre}}</td>
                                        <td class="vertical-td">{{ i.imp_porcentaje|unlocalize}} %</td>
                                        <td class="vertical-td">
                                            <div class="btn-group">
                                                <button onclick="ajus_cargar_impuesto('{% url "dashboard_app:url_cargar_impuestos" %}', {{ i.imp_id }}, this)" class="btn bg-navy btn-xs" title="{% trans 'Editar' %}"><i class="glyphicon glyphicon-edit"></i></button>
                                                <button onclick="prod_eliminar_objetos('{% url "dashboard_app:url_eliminar_impuestos" %}?id={{ i.imp_id }}', 'IVA', 'tabla_impuesto', this)" class="btn btn-danger btn-xs" title="{% trans 'Eliminar' %}"><i class="fa fa-trash-o"></i></button>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock contenido %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#menu_ajustes').addClass("active");
            $('#menu_ajustes_impuesto').addClass("active");
            $('#menu_ajustes_impuesto').children('a').removeAttr('href');

            var table = $('#tabla_impuesto').DataTable( {
                lengthChange: false,
                bSort: false
            });
        });
    </script>
{% endblock scripts %}